name: Create PR when new release branch is created

on:
  push:

jobs:
  auto-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@1.0.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: "RELEASE-v"
          PULL_REQUEST_BRANCH: "master"
