name: Create PR when new release branch is created

on:
  push:
    branches-ignore:
      - master

jobs:
  auto-pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@1.0.0
    
    - name: Create pull request
      uses: thomaseizinger/create-pull-request@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        title: "New release"
